[tasks.unit-tests]
script = ''' 
files=$(git ls-files --exclude-standard --cached --others | xargs -I{} basename {} | grep "_unit_test" | sed 's/\.rs$//')
for file in $files; do
cargo test --test $file
done
'''
script_runner = "@shell"

[tasks.prop-tests]
script = ''' 
files=$(git ls-files --exclude-standard --cached --others | xargs -I{} basename {} | grep "_prop_test" | sed 's/\.rs$//')
for file in $files; do
cargo test --test $file
done
'''
script_runner = "@shell"

[tasks.integration-tests]
script = ''' 
files=$(git ls-files --exclude-standard --cached --others | xargs -I{} basename {} | grep "_integration_test" | sed 's/\.rs$//')
for file in $files; do
cargo test --test $file
done
'''
script_runner = "@shell"
